# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'EndlessReminder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EndlessReminder
  pod 'RealmSwift', '=10.1.4'

  target 'EndlessReminderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EndlessReminderUITests' do
    # Pods for testing
  end

end

